<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--Dinamic
    var using xacro-->
    <xacro:property name="base_length" value="0.7" />
    <xacro:property name="base_width" value="0.75" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="upper_base_length" value="0.4" />
    <xacro:property name="upper_base_width" value="0.4" />
    <xacro:property name="upper_base_height" value="0.8"/>
    <!-- Define links -->
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
            <material name="green" />
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
            <material name="green" />
        </collision>

        <xacro:box_inertia m="5.0" l="${base_length}" w="${base_width}" h="${base_height}"
            xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
    </link>

    <link name="upper_base_link">
        <visual>
            <geometry>
                <box size="${upper_base_length} ${upper_base_width} ${upper_base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="red" />
        </visual>
    

        <collision>
            <geometry>
                <box size="${upper_base_length} ${upper_base_width} ${upper_base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="5.0" l="${upper_base_length}" w="${upper_base_width}" h="${upper_base_height}"
            xyz="0 0 ${base_height + upper_base_height / 2.0}" rpy="0 0 0" />
    </link>
    <!--Function
    with xacro-->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
                <material name="blue" />
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" h="${wheel_length}" r="${wheel_radius}"
                xyz="0 0 0" rpy="${pi/2.0} 0 0" />
        </link>
    </xacro:macro>

    <!-- Use the macro to create wheel links -->
    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:shpere_inertia m="5.0" r="${wheel_radius / 2.0}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!-- Define joints -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="upper_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="upper_base_link" />
        <origin xyz="0 0 ${base_height + upper_base_height / 2.0}" rpy="0 0 0" />
    </joint>

</robot>