controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]
    wheel_separation: 0.68545  # Tính từ origin của base_left_wheel_joint và base_right_wheel_joint
    wheel_radius: 0.1         # Từ xacro property
    publish_rate: 50.0
    use_stamped_vel: false